### ISSUE TITLE
trufflehog pre-commit check fails when pushing new branches

### ISSUE THREAD

**Issue by JacobHayes** [artigraph/artigraph#188]
**Describe the bug**

Pushing up a new branch fails the trufflehog pre-commit check with:

```
Traceback (most recent call last):
  File "/Users/jacobhayes/src/github.com/artigraph/artigraph/.direnv/python-3.9.7/bin/trufflehog", line 8, in <module>
    sys.exit(main())
  File "/Users/jacobhayes/src/github.com/artigraph/artigraph/.direnv/python-3.9.7/lib/python3.9/site-packages/truffleHog/truffleHog.py", line 92, in main
    output = find_strings(args.git_url, args.since_commit, args.max_depth, args.output_json, args.do_regex, do_entropy,
  File "/Users/jacobhayes/src/github.com/artigraph/artigraph/.direnv/python-3.9.7/lib/python3.9/site-packages/truffleHog/truffleHog.py", line 337, in find_strings
    branches = repo.remotes.origin.fetch()
  File "/Users/jacobhayes/src/github.com/artigraph/artigraph/.direnv/python-3.9.7/lib/python3.9/site-packages/git/remote.py", line 792, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/Users/jacobhayes/src/github.com/artigraph/artigraph/.direnv/python-3.9.7/lib/python3.9/site-packages/git/remote.py", line 688, in _get_fetch_info_from_stderr
    with open(osp.join(self.repo.common_dir, 'FETCH_HEAD'), 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/ss/tgmzwbx52y35qpr7rzrtv8ym0000gn/T/tmpsxmkab_e/.git/FETCH_HEAD'
```

**To Reproduce**
Create a new branch, add a commit, and `git push -u origin <branchname>`

**Comment by JacobHayes** [comment]
Removed from pre-commit in https://github.com/artigraph/artigraph/commit/0808f6dba97f469be4764458fa898b432fc79faf. It's still run in CI for each commit.
